spring.application.name=SecurityExample

spring.datasource.url=jdbc:mysql://localhost:3306/world

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.username=root

spring.datasource.password=root

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto= update


server.port=2000

spring.security.user.name=sani
spring.security.user.password=sansak2002